### ISSUE TITLE
Can't resolve 'module' in webp-wasm/bridge.js

### ISSUE THREAD

**Issue by hcxmj** [jhuckaby/webp-wasm#1]
hello author,When I introduce and use it in react, the problem of Can't resolve 'module' keeps appearing. I don't know how to deal with it. I want to consult.
my development environment:
 "react": "^18.2.0",
"webpack": "^5.74.0",
<img width="716" alt="image" src="https://user-images.githubusercontent.com/58494807/226507099-c886e481-5d06-4a13-a621-3bd50b74eca3.png">

**Comment by jhuckaby** [comment]
This module is for Node.js (server-side) use only.  It will not work with React or Webpack.  You need to find a client-side WebP/WASM module instead.  Try [Squoosh](https://github.com/GoogleChromeLabs/squoosh) maybe?  Their WebP WASM implementation is client-side.

Also, you should know that WebP is [supported in all major browsers](https://caniuse.com/webp) now anyway, so you may not even need a WebP library.  Just use WebP images directly.

Hope this helps.

**Comment by hcxmj** [comment]
> 
Although the current mainstream browsers support webp, when the webp animation is displayed in the iOS environment, the first round of rendering will be obviously stuck, so I want to try whether the WASM method can accelerate and reduce the freeze, and the android environment is obviously better. I Trying to solve the problem of relying on node built-in modules through webpack configuration

**Comment by hcxmj** [comment]
> 

Although the current mainstream browsers support webp, when the webp animation is displayed in the iOS environment, the first round of rendering will be obviously stuck, so I want to try whether the WASM method can accelerate and reduce the freeze, and the android environment is obviously better. I Trying to solve the problem of relying on node built-in modules through webpack configuration

**Comment by jhuckaby** [comment]
Check out [Squoosh](https://github.com/GoogleChromeLabs/squoosh).  Their WebP WASM runs in the browser.

**Comment by hcxmj** [comment]
> Check out [Squoosh](https://github.com/GoogleChromeLabs/squoosh). Their WebP WASM runs in the browser.

ok,Thank you

**Comment by hcxmj** [comment]
> Check out [Squoosh](https://github.com/GoogleChromeLabs/squoosh). Their WebP WASM runs in the browser.
In addition, I would like to know more about you. I think Squoosh only does some compression and optimization of webp resources, and does not directly improve the decoding efficiency. The webp-wasm library you encapsulate contains whether the decode uses Assembly to improve the decoding efficiency. improve rendering

**Comment by jhuckaby** [comment]
Alas, I am sorry, but my library doesn't do anything special.  I just copied down the Squoosh WebP WASM files, and am loading them in Node.js, instead of the browser.  I did not add any features or increase decoding efficiency.  My code is literally a copy of Squoosh's library.  Sorry 😞

**Comment by hcxmj** [comment]
> Alas, I am sorry, but my library doesn't do anything special. I just copied down the Squoosh WebP WASM files, and am loading them in Node.js, instead of the browser. I did not add any features or increase decoding efficiency. My code is literally a copy of Squoosh's library. Sorry 😞


Thank you very much for your ideas
