### ISSUE TITLE
target size being ignored?

### ISSUE THREAD

**Issue by ash-hashtag** [jhuckaby/webp-wasm#4]
Or what is the proper way to use target size?

**Comment by jhuckaby** [comment]
I honestly don't know.  That value is passed straight through to the [Squoosh](https://github.com/GoogleChromeLabs/squoosh) WebP WASM library.  I copied the list of available parameters from this document: https://developers.google.com/speed/webp/docs/api#advanced_encoding_api

I suspect not all of them are implemented in the WASM version 😞

I'm sorry.
